### ISSUE TITLE
Lifecycle methods are not executing

### ISSUE THREAD

**Issue by jojjesv** [ibitcy/react-stores#16]
I'd like to update my shared state whenever my props are updated, like this:

```
  storeComponentWillReceiveProps(nextProps: Props) {
    let { sharedState } = this
    let { markers } = sharedState
    this.checkMissingMarkers(markers, (nextProps.selectedTreatment || {} as any).markers)
  }

  checkMissingMarkers(oldMarkers: Marker[], newMarkers: Marker[]) {
    const { props } = this
    if (newMarkers.length && newMarkers.length > oldMarkers.length) {
      this.addMissingMarkers(newMarkers)
    }
  }

  /**
   * Invoked if new markers appeared in props (maybe just finished fetching treatment).
   */
  addMissingMarkers(syncWith: Marker[]) {
    console.log("Updating shared state with new markers", syncWith)
    //  this.setSharedState(...)
  }
```
Though `storeComponentWillReceiveProps` never fires. I can log the props in `render` and it works just fine, they look as expected. I've also tried with `getSnapshotBeforeUpdate` and `componentWillReceiveProps`, and I've not combined any of the three as I'm aware they don't play well together.

package.json:
```
{
  "name": "******",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "classnames": "^2.2.6",
    "js-cookie": "^2.2.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-router": "^5.0.0",
    "react-router-dom": "^5.0.0",
    "react-scripts": "2.1.8",
    "react-stores": "^2.10.1",
    "uuid": "^3.3.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "@types/classnames": "^2.2.7",
    "@types/js-cookie": "^2.2.2",
    "@types/node": "^11.12.2",
    "@types/react": "^16.8.10",
    "@types/react-dom": "^16.8.3",
    "@types/react-router": "^4.4.5",
    "@types/react-router-dom": "^4.3.1",
    "@types/uuid": "^3.4.4",
    "node-sass": "^4.11.0",
    "typescript": "^3.4.1"
  }
}
```

The component class extends `StoreComponent<Props, State, StoreState>`.

Running Chrome Version 73.0.3683.86 (Official Build) (64-bit) macOS.

Any ideas?

**Comment by ruslanchek** [comment]
Hi! StoreComponent and its lifecycle is deprecated since 2.x. However I've just updated demo page and implement test with `storeComponentWillReceiveProps()` and it seems to be working fine. About your `this.setSharedState` and `this.sharedState`, how are they implemented?

**Comment by ruslanchek** [comment]
I have found that you’re using something looks like an anti-pattern.  Consider putting your markers logic somewhere out of component life cycles.  You can try to make MarkerActions class with your business logic and fill up your store there.  In your component, you have to use pure data from your store.
